name: clynamic
description: dynamize!

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.13.0 <4.0.0"

dependencies:
  url_strategy: ^0.2.0
  flutter:
    sdk: flutter
  crypto: ^3.0.3
  font_awesome_flutter: ^10.5.0
  url_launcher: ^6.1.14
  cached_network_image: ^3.2.3
  octo_image: ^1.0.2
  shimmer: ^3.0.0
  http: ^1.1.0
  html: ^0.15.4
  relative_time: ^4.0.1

dev_dependencies:
  flutter_lints: ^2.0.0

  # dart run flutter_native_splash:create
  flutter_native_splash: ^2.1.3+1

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_native_splash:
  color: "#1d1b1e"
  image: "assets/logo.png"
