# See more options at https://pub.dev/packages/swagger_parser
swagger_parser:
  # Make sure that the server is running.
  # schema_path: api.json
  schema_url: http://127.0.0.1:6001/swagger-ui/api.json

  output_directory: lib/api

  freezed: true
  unknown_enum_value: false
  required_by_default: false
